### ISSUE TITLE
Getting hackathon data, a story

### ISSUE THREAD

**Issue by wildmolasses** [Great-Hill-Corporation/trueblocks-core#1085] opened 2019-04-22 13:22 UTC
Went here: https://dappradar.com/app/944/my-crypto-heroes
Got list of contract addresses
Thought, how am I gonna get the data?
Thought, hmm, quickblocks code in flux, might still have some issues like byte shifted articulated data.
Considered etherscan, blockscout. Didn’t feel like writing api fetch script, getting around api limits, and parsing abis myself.
Thought I couldn’t use wildmolasses machine because the docker image is only scraped to 5m+.
Realized then that @tjayrush had been scraping it outside of docker and that I could use that index (on wildmolasses machine)

Couldn’t `chifra list` / `chifra export` from wildmolasses user, so `su jrush`.

Tried some `list` and `export`. Export takes a long time and no feedback — I thought maybe something was wrong with my file redirect to leave it hanging. But it just takes a while. But actually, now it's a couple days later and still waiting on one result set. (see `tmux a -t hackathon-data` on jrush user)

I wrote a script to help me retrieve the data for 22 individual contracts. I have to run the script from the jrush user, without using sudo.

```bash
contracts=("HeroPresale 0x946048A75Af11C300A274344887eC39452218B3d"
    "HeroGateway 0x138a35ee20e40f019e7e7c00386ab2ef42d66d1e"
    "HeroCrowdsale 0xa1d2c7e6de2fa512f1fdf486ca17ab79b4dc5d01"
    "HeroAsset 0x273f7F8E6489682Df756151F5525576E322d51A3"
    "SmartContract5 0x9a7956dff83d5e94e8b4e9c6bbd7a40a9c89ebf7"
    "GumGateway 0xa30cbce69f520bf2a34c5c15193b7f5afe427a26"
    "ExtensionGateway 0x46fc7b42f4522bfbd8b4565130aaed1e407d9957"
    "ExtensionAsset 0xdceaf1652a131F32a821468Dc03A92df0edd86Ea"
    "MCHEMONTGateway 0x4B9F5347c489D9EE91787B7e9f678d354324878F"
    "MCHEMONTGateway2 0x97D99Db7a938Ad4f6dD8D607dEB2083f1B36db0B"
    "SmartContract11 0xc045c0bd4a26160a85039dbaf9c1ab4cd93249d3"
    "SmartContract12 0xAdcD61c78f052cF38ab9E67c353deC1DA14E04B3"
    "MCHDailyActionV2 0xfD0174784EbCe943bdb8832Ecdea9Fea30e7C7A9"
    "MCHPrime 0xdEe34Cd48D77183B3E70F4f9Ea2718c89bFeFeB4"
    "SmartContract15 0x20E94588391dB2Dce6570E700474Fb6702942720"
    "SmartContract16 0x8D00BBf3620950ccd660EF7B48F24951ECB3A176"
    "LandSectorAsset 0x75A640661B78021E4b1A58577E4831C7eDB571AF"
    "MCHLandPool 0x4A627B324189014fA757eD7cc730b180879232D7"
    "MCHGUMGatewayV6 0x7a2aB08612bd07c8BF661883e21240F49B58E944"
    "LandSectorAsset2 0x617913dd43dbdf4236b85ec7bdf9adfd7e35b340"
    "HeroGatewayV2 0x185b257AA51Fdc45176cF1FfaC6a0bFB5cF28afD"
    "SmartContract22 0x211b3c1f7893685e395553da61cf32c10764c23d")

for ((i = 0; i < ${#contracts[@]}; i++)); do
    filename=${contracts[i]% *};
    address=${contracts[i]#* };
    echo "exporting $address to $filename.json";
    chifra export $address > $filename.json
done
```

I love when it runs through the index files (the “list” phase). Such a good feeling to see that list get parsed so quickly. I like the output to my screen.

Every time, I see that “price database has been updated… 387914 records.” That record count throws me every time. I at first think it’s the record count of my export. But it's a status message about the price database. I know it obviously says "price database." But my head is in "appearance record number," not "price record number."

Export could use a progress indicator. After all, we know how many records we’re expected to retrieve. But it might be laborious to insert this feature.

Pulling files off to check them as they're done. Getting JSON errors.

HeroGateway.json
```
Error: Parse error on line 30:
...00000000000000000}{  "hash": "0x04a2a
---------------------^
Expecting 'EOF', '}', ',', ']', got ‘{'
```

Some considerations from call:
- output flag instead of file redirect (https://github.com/Great-Hill-Corporation/quickBlocks/issues/1088)
- JSON error already fixed (https://github.com/Great-Hill-Corporation/quickBlocks/pull/1086/commits/6a33a6e1cfa59bdefac0718676116f079ab95e9f)

**Comment by tjayrush** [comment] 2019-04-22 15:44
> Thought, hmm, quickblocks code in flux, might still have some issues like byte shifted articulated data.

What is 'byte shifted articulated data'? Is that documented with an issue? Please link that issue here.

**Comment by tjayrush** [comment] 2019-04-22 15:48
> Couldn’t `chifra list` / `chifra export` from wildmolasses user, so `su jrush`.

I'm somewhat surprised by this. It should have worked if you had your `cachePath` set correctly in `~/.quickBlocks/quickBlocks.toml`.

Be a bit careful though -- don't use `chifra list`, `chifra export`, or `chifra scrape` -- they should only run once so as to not corrupt data (although `list` and `export` only read data, they do write to cache).

Just see if you can run `getBlock 1001001`. If that works, then the issue is the setting in the config file. If that doesn't work, then let's make an issue about running as one user on a machine where another user has done the scrape.

We should also think about how to build test cases to check what happens when two users on the same machine try to (a) scrape, (b) list, (c) export. It should work (the code is there), but it has not been tested.

**Comment by tjayrush** [comment] 2019-04-22 15:50
> But actually, now it's a couple days later and still waiting on one result set. (see `tmux a -t hackathon-data` on jrush user)

100% this is a bug. Can you link to the issue if there is one, and create an issue if not.

**Comment by tjayrush** [comment] 2019-04-22 15:51
> I see that “price database has been updated… 387914 records.” That record count throws me every time. I at first think it’s the record count of my export. But it's a status message about the price database. I know it obviously says "price database." But my head is in "appearance record number," not "price record number."

https://github.com/Great-Hill-Corporation/quickBlocks/issues/1087

**Comment by wildmolasses** [comment] 2019-04-23 05:50
> > Thought, hmm, quickblocks code in flux, might still have some issues like byte shifted articulated data.
> 
> What is 'byte shifted articulated data'? Is that documented with an issue? Please link that issue here.

It used to be an issue in this repo, but it was moved: https://github.com/Great-Hill-Corporation/tokenomics/issues/140



> > Couldn’t `chifra list` / `chifra export` from wildmolasses user, so `su jrush`.
> 
> I'm somewhat surprised by this. It should have worked if you had your `cachePath` set correctly in `~/.quickBlocks/quickBlocks.toml`.

What is "correctly" here? Should it be set to the same cache path as yours?

> Be a bit careful though -- don't use `chifra list`, `chifra export`, or `chifra scrape` -- they should only run once so as to not corrupt data (although `list` and `export` only read data, they do write to cache).

This part I'm not understanding. I need to run `chifra list` and `chifra export`.

**Comment by tjayrush** [comment] 2019-04-27 01:08
There's a couple of issues here, I guess.

1. Bad parser data
2. Two users on the same machine sharing a 'scraper' folder
3. Same as two, but discussing file locking

**Comment by tjayrush** [comment] 2019-09-06 21:36
Closing as this data has been copied over to anotehr issue.

**Closed by tjayrush** 2019-09-06 21:36 UTC
Labels: TA-blockScrape, TX-scraper-metrics, delayed
